import {
  getBgTheme,
  getLanguage,
  getColorTheme,
  getFontSize,
  getAllowMessages,
  getHideMessages,
  getShowRead,
  getFindByEmail,
  getFindByPhone,
  getAllowBehavioralAds,
  getAllowLocationAds,
  getQualityFilter,
  getColorContrast,
  getReduceMotion,
  getAddImgExpl,
  getDataSaver,
  getAutoplay,
  getIsPrivate,
  getProtectVideo,
  getTagSensitiveMedia,
  getDisplaySensitiveMedia,
  getAddLocationInfo,
  getMuteNotFollowing,
  getMuteNotFollower,
  getMuteNewAccount,
  getMuteDefaultProfile,
  getMuteEmailAuthenticated,
  getMutePhoneAuthenticated,
  getProtectRenewPassword,
  getTwoFactorAuthentication,
  getHideLabel,
  getConnectedApps,
  getSessions,
  getLoginHistory,
  getDevices,
  getConnectedAccounts,
  getCanbeInvited,
  getDelegate,
  getDelegateGroups,
  getDelegateMembers,
  getAllowTagging,
  getAllowTaggingWhom,
  getTopics,
} from "./settingsSelectors";
import { getIsLoggedIn } from "./loginSelector";
import {
  getUser,
  getProfileImage,
  getGender,
  getUserId,
  getPhone,
  getEmail,
  getCountry,
  getBirth,
} from "./userSelector";
import {
  getSigninInfo,
  getSigninUser,
  getSigninUserSettings,
} from "./signinSelector";

export {
  // userSettings
  getBgTheme,
  getLanguage,
  getColorTheme,
  getFontSize,
  getAllowMessages,
  getHideMessages,
  getShowRead,
  getFindByEmail,
  getFindByPhone,
  getAllowBehavioralAds,
  getAllowLocationAds,
  getQualityFilter,
  getColorContrast,
  getReduceMotion,
  getAddImgExpl,
  getDataSaver,
  getAutoplay,
  getIsPrivate,
  getProtectVideo,
  getTagSensitiveMedia,
  getDisplaySensitiveMedia,
  getAddLocationInfo,
  getMuteNotFollowing,
  getMuteNotFollower,
  getMuteNewAccount,
  getMuteDefaultProfile,
  getMuteEmailAuthenticated,
  getMutePhoneAuthenticated,
  getProtectRenewPassword,
  getTwoFactorAuthentication,
  getHideLabel,
  getConnectedApps,
  getSessions,
  getLoginHistory,
  getDevices,
  getConnectedAccounts,
  getCanbeInvited,
  getDelegate,
  getDelegateGroups,
  getDelegateMembers,
  getAllowTagging,
  getAllowTaggingWhom,
  getTopics,
  // login
  getIsLoggedIn,
  // user
  getUser,
  getProfileImage,
  getGender,
  getUserId,
  getPhone,
  getEmail,
  getCountry,
  getBirth,
  // signin
  getSigninInfo,
  getSigninUser,
  getSigninUserSettings,
};
