import About from "./About/About";
import SettingsLandingPage from "./SettingsLandingPage/SettingsLandingPage";
import {
  AccountPage,
  AccountInfoPage,
  DeactivatePage,
  GenderPage,
  ScreenNamePage,
  PhonePage,
  EmailPage,
  CountryPage,
  LanguagePage,
  AgePage,
  PasswordPage,
  DownloadDataPage,
} from "./Account";
import {
  SecurityAndAccountAccessPage,
  SecurityPage,
  AppsAndSessionsPage,
  LoginVerficationPage,
  IdVerficationPage,
  ConnectedAppsPage,
  SessionsPage,
  LoginHistoryPage,
  DevicesPage,
  ConnectedAccountsPage,
  DelegatePage,
  DelegateGroupsPage,
  DelegateMembersPage,
} from "./SecurityAndAccountAccess";
import {
  PrivacyAndSafetyPage,
  MuteAndBlockPage,
  AudienceAndTaggingPage,
  YourPostsPage,
  ContentYouSeePage,
  MessageSettingPage,
  ContactsPage,
  AdsPreferencesPage,
  LocationInfoPage,
  LocationPage,
  NotificationAdvancedFilters,
  TaggingPage,
  TopicsPage,
  BlockedAllPage,
  MutedAllPage,
  MutedKeywordsPage,
  AddMutedKeywordsPage,
  ContactsDashboardPage,
  InterestsPage,
  AudiencesPage,
  LocationsPage,
} from "./PrivacyAndSafety";
import {
  NotificationsPage,
  NotificationPreferencePage,
  NotificationFilterPage,
  EmailNotificationsPage,
  PushNotificationsPage,
} from "./Notifications";
import {
  AccessibilityAndDisplayAndLanguagesPage,
  AccessibilityPage,
  LanguagesPage,
  DataPage,
  AutoplayPage,
  DisplayPage,
} from "./AccessibilityAndDisplayAndLanguages";
export {
  SettingsLandingPage,
  AccountPage,
  SecurityAndAccountAccessPage,
  PrivacyAndSafetyPage,
  NotificationsPage,
  AccessibilityAndDisplayAndLanguagesPage,
  AppsAndSessionsPage,
  MuteAndBlockPage,
  NotificationPreferencePage,
  SecurityPage,
  AccountInfoPage,
  DeactivatePage,
  AudienceAndTaggingPage,
  YourPostsPage,
  ContentYouSeePage,
  MessageSettingPage,
  ContactsPage,
  AdsPreferencesPage,
  LocationInfoPage,
  NotificationFilterPage,
  AccessibilityPage,
  LanguagesPage,
  DataPage,
  AutoplayPage,
  LocationPage,
  NotificationAdvancedFilters,
  LoginVerficationPage,
  IdVerficationPage,
  GenderPage,
  ScreenNamePage,
  PhonePage,
  EmailPage,
  CountryPage,
  LanguagePage,
  AgePage,
  PasswordPage,
  DownloadDataPage,
  ConnectedAppsPage,
  SessionsPage,
  LoginHistoryPage,
  DevicesPage,
  ConnectedAccountsPage,
  DelegatePage,
  About,
  DelegateGroupsPage,
  DelegateMembersPage,
  TaggingPage,
  TopicsPage,
  BlockedAllPage,
  MutedAllPage,
  MutedKeywordsPage,
  AddMutedKeywordsPage,
  ContactsDashboardPage,
  InterestsPage,
  AudiencesPage,
  LocationsPage,
  EmailNotificationsPage,
  PushNotificationsPage,
  DisplayPage,
};
