import {
  FaEarthAfrica as africa,
  FaEarthAmericas as americas,
  FaEarthAsia as asia,
  FaEarthEurope as europe,
  FaEarthOceania as oceania,
  FaRegEnvelope as message,
} from "react-icons/fa6";

import { BsEnvelopePlus as addMessage } from "react-icons/bs";

import { GiEarthAsiaOceania as world } from "react-icons/gi";

import {
  LuUserCheck as usercheck,
  LuBadgeCheck as badgecheck,
  LuAtSign as atsign,
  LuImage as image,
  LuListTodo as vote,
  LuSmile as emoji,
  LuCalendarClock as reserve,
  LuMapPin as location,
  LuBell as alarm,
  LuSettings as setting,
  LuMoreHorizontal as more,
  LuPin as pin,
  LuBellOff as block,
  LuFlag as report,
  LuTrash2 as delConversation,
  LuArrowLeft as backward,
  LuUser as users,
  LuUsers as groups,
  LuMessageSquare as conversations,
  LuCircle as circleEmpty,
  LuCheckCircle2 as circleChecked,
  LuSquare as squareEmpty,
  LuChevronDownSquare as squareChecked,
  LuInfo as info,
  LuSend as talkReply,
  LuCopy as copy,
  LuX as close,
  LuChevronRight as forward,
  LuUser2 as account,
  LuKeyRound as password,
  LuDownload as download,
  LuHeartCrack as deactivate,
  LuLock as security,
  LuCopy as app,
  LuArrowLeftRight as connect,
  LuUsers2 as delegate,
  LuPenLine as write,
  LuText as content,
  LuVolumeX as mute,
  LuContact as contact,
  LuArrowUpRightSquare as ads,
  LuSlidersHorizontal as filter,
  LuSettings2 as preference,
  LuEyeOff as accessibility,
  LuPen as display,
  LuBarChart3 as chart,
  LuArrowUpRight as link,
} from "react-icons/lu";

import { PiPersonSimpleCircleLight as shortcut } from "react-icons/pi";

import { TbCameraPlus as addImage } from "react-icons/tb";

const ICONS = {
  replyOptions: {
    all: {
      africa,
      americas,
      asia,
      europe,
      oceania,
    },
    other: {
      following: usercheck,
      authenticated: badgecheck,
      mention: atsign,
    },
  },
  writeOptions: {
    image,
    vote,
    emoji,
    reserve,
    location,
  },
  notificationIcons: {
    alarm,
  },
  messageIcons: {
    setting,
    addMessage,
    more,
    pin,
    block,
    report,
    delConversation,
    backward,
    users,
    groups,
    conversations,
    circleEmpty,
    circleChecked,
    squareEmpty,
    squareChecked,
    info,
    talkReply,
    talkReport: report,
    talkCopy: copy,
    talkDelete: delConversation,
  },
  profileIcons: {
    addImage,
    deleteImage: close,
  },
  searchIcons: {
    backward,
    more,
  },
  settingsIcons: {
    forward,
    account,
    password,
    download,
    deactivate,
    security,
    app,
    connect,
    delegate,
    write,
    content,
    mute,
    message,
    contact,
    location,
    ads,
    filter,
    preference,
    accessibility,
    display,
    world,
    chart,
    shortcut,
    link,
  },
};

export default ICONS;
